apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: petclinic-db-credentials
  namespace: default
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: petclinic-db-credentials
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: eksmedz/petclinic/db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: eksmedz/petclinic/db-credentials
        property: password
