apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: {{ include "visits-service.fullname" . }}-canary-check
spec:
  metrics:
    - name: canary-restart-count
      interval: 30s
      count: 3
      successCondition: result[0] == 0
      failureLimit: 1
      provider:
        prometheus:
          address: http://prometheus-operated.monitoring.svc.cluster.local:9090
          query: |
            sum(increase(kube_pod_container_status_restarts_total{namespace="{{ .Release.Namespace }}", pod=~"{{ include "visits-service.fullname" . }}.*"}[2m]))
