apiVersion: v1
kind: ResourceQuota
metadata:
  name: eksmedz-dev-quota
  namespace: eksmedz-dev
spec:
  hard:
    requests.cpu: "6"
    requests.memory: 6Gi
    limits.cpu: "12"
    limits.memory: 8Gi
    pods: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: eksmedz-dev-limitrange
  namespace: eksmedz-dev
spec:
  limits:
    - type: Container
      default:
        cpu: 500m
        memory: 512Mi
      defaultRequest:
        cpu: 250m
        memory: 256Mi
      max:
        cpu: "1"
        memory: 1Gi
      min:
        cpu: 50m
        memory: 64Mi
